# Generated by Django 3.0.4 on 2020-03-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='point',
            name='modified_date',
        ),
        migrations.AddField(
            model_name='point',
            name='timestamp',
            field=models.BigIntegerField(default=0),
        ),
    ]
