# Generated by Django 3.0.4 on 2020-03-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200318_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='timestamp',
            field=models.BigIntegerField(default=-1),
        ),
    ]
