# Generated by Django 3.0.4 on 2020-03-18 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200318_1958'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='point',
            unique_together={('trip', 'lon', 'lat', 'timestamp')},
        ),
    ]
