# Generated by Django 2.2.10 on 2020-03-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200318_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='avg_speed',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='distance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='max_speed',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
