# Generated by Django 3.0.4 on 2020-03-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200319_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='was_paused',
            field=models.BooleanField(default=False),
        ),
    ]
