# Generated by Django 3.0.4 on 2020-03-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_point_was_paused'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='last_pos_lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='trip',
            name='last_pos_lon',
            field=models.FloatField(default=0.0),
        ),
    ]
