# Generated by Django 3.0.4 on 2020-03-19 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200319_1428'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='point',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='Point60',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.FloatField(default=0.0)),
                ('lat', models.FloatField(default=0.0)),
                ('timestamp', models.BigIntegerField(default=0)),
                ('was_paused', models.BooleanField(default=False)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Trip')),
            ],
            options={
                'abstract': False,
                'unique_together': {('trip', 'lon', 'lat', 'timestamp')},
            },
        ),
    ]
