# Generated by Django 3.0.4 on 2020-03-19 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200319_1503'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='point',
            unique_together={('trip', 'lon', 'lat', 'timestamp')},
        ),
    ]
