# Generated by Django 2.2.10 on 2020-03-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200319_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='number_of_points',
            field=models.IntegerField(default=0),
        ),
    ]
